# file: roles/mysql/tasks/install.yml

- name: MySql packages are installed
  yum: pkg={{ item }}
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
  notify:
    - Start the MySQL service